version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: testTec
    environment:
      POSTGRES_USER: yme
      POSTGRES_PASSWORD: yme
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
